spring:
  datasource:
    url:  jdbc:postgresql://localhost:30003/dcs
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  show-sql: true

server:
  error:
    include-message: always
    include-binding-errors: always
