version: '3.8'

services:
  db:
    image: postgres:alpine
    ports:
      - "30003:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password